apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: wip-deep-learning-server-v2-00061-hrl
  namespace: '275975834834'
  selfLink: /apis/serving.knative.dev/v1/namespaces/275975834834/revisions/wip-deep-learning-server-v2-00061-hrl
  uid: 61d7d947-c560-4e8b-9cac-1a50e847a62b
  resourceVersion: AAYna8sqG+E
  generation: 1
  creationTimestamp: '2024-11-21T12:55:59.981320Z'
  labels:
    client.knative.dev/nonce: feb2e8e2-cb33-4459-9b35-237a4a72d0ca
    commit-sha: 6730d56033fbe0352537f1028464a36c03b2cd17
    gcb-build-id: d54c0a50-d582-4a42-8d0d-7a9cb06b3842
    gcb-trigger-id: 2b2bf68b-2179-4aca-a621-4f086cce043e
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    serving.knative.dev/configuration: wip-deep-learning-server-v2
    serving.knative.dev/configurationGeneration: '61'
    serving.knative.dev/service: wip-deep-learning-server-v2
    serving.knative.dev/serviceUid: 980ea830-4c8d-4f0d-8b6c-0546da0a1baf
    serving.knative.dev/route: wip-deep-learning-server-v2
    cloud.googleapis.com/location: asia-northeast1
    run.googleapis.com/startupProbeType: Custom
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/startup-cpu-boost: 'false'
    run.googleapis.com/execution-environment: gen1
    run.googleapis.com/operation-id: 2fc48cbc-c40c-48e2-b944-595dd73d4b95
    autoscaling.knative.dev/maxScale: '5'
    serving.knative.dev/creator: knut043mbm@gmail.com
  ownerReferences:
  - kind: Configuration
    name: wip-deep-learning-server-v2
    uid: dbb886d8-4b3a-4c6d-8f90-4fe922ea8104
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 1000
  timeoutSeconds: 60
  serviceAccountName: image-search@what-is-pill.iam.gserviceaccount.com
  containers:
  - name: placeholder-1
    image: gcr.io/what-is-pill/wip-deep-learning-server-v2@sha256:27291fd070985ee9132ee00e2ee504f8c1c75bee94cd10da6cfda47ed39ffd14
    args:
    - DL_SERVER_PORT=16262
    ports:
    - name: http1
      containerPort: 16262
    env:
    - name: DL_SERVER_PORT
      value: '16262'
    - name: GOOGLE_CLOUD_LOGGING_DISABLE
      value: 'true'
    resources:
      limits:
        cpu: 1000m
        memory: 1280Mi
    startupProbe:
      timeoutSeconds: 60
      periodSeconds: 240
      failureThreshold: 1
      tcpSocket:
        port: 16262
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-11-21T12:56:22.561500Z'
  - type: Active
    status: 'True'
    lastTransitionTime: '2024-11-21T12:56:22.617032Z'
    severity: Info
  - type: ContainerHealthy
    status: 'True'
    message: Container became healthy in 17.414972s.
    lastTransitionTime: '2024-11-21T12:56:22.528439Z'
  - type: ContainerReady
    status: 'True'
    message: Container image import completed.
    lastTransitionTime: '2024-11-21T12:56:01.968918Z'
  - type: ResourcesAvailable
    status: 'True'
    message: Revision deployment finished in 2.853431s. Checking container health.
    lastTransitionTime: '2024-11-21T12:56:04.818460Z'
  logUrl: https://console.cloud.google.com/logs/viewer?project=what-is-pill&resource=cloud_run_revision/service_name/wip-deep-learning-server-v2/revision_name/wip-deep-learning-server-v2-00061-hrl&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22wip-deep-learning-server-v2%22%0Aresource.labels.revision_name%3D%22wip-deep-learning-server-v2-00061-hrl%22
  imageDigest: gcr.io/what-is-pill/wip-deep-learning-server-v2@sha256:27291fd070985ee9132ee00e2ee504f8c1c75bee94cd10da6cfda47ed39ffd14
  containerStatuses:
  - name: placeholder-1
    imageDigest: gcr.io/what-is-pill/wip-deep-learning-server-v2@sha256:27291fd070985ee9132ee00e2ee504f8c1c75bee94cd10da6cfda47ed39ffd14
