apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: image-search-00065-zvq
  namespace: '275975834834'
  selfLink: /apis/serving.knative.dev/v1/namespaces/275975834834/revisions/image-search-00065-zvq
  uid: 04b81008-9dec-4ebf-afa0-012712c60868
  resourceVersion: AAYna8bDMSQ
  generation: 1
  creationTimestamp: '2024-11-21T12:55:03.670888Z'
  labels:
    client.knative.dev/nonce: 40802712-1ce5-4d69-aef2-31dc3e858cd2
    serving.knative.dev/configuration: image-search
    serving.knative.dev/configurationGeneration: '65'
    serving.knative.dev/service: image-search
    serving.knative.dev/serviceUid: a755b647-ae5c-4ff6-8247-51c7b5e5a3c4
    goog-managed-by: cloudfunctions
    goog-cloudfunctions-runtime: nodejs20
    cloud.googleapis.com/location: asia-northeast1
    serving.knative.dev/route: image-search
    run.googleapis.com/startupProbeType: Custom
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/startup-cpu-boost: 'false'
    cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
    run.googleapis.com/build-source-location: '{"worker":"gs://run-sources-what-is-pill-asia-northeast1/image-search/function-source.zip#1732193505519377"}'
    serving.knative.dev/creator: knut043mbm@gmail.com
    run.googleapis.com/build-function-target: '{"worker":"imageSearch"}'
    run.googleapis.com/base-images: '{"worker":"asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20"}'
    run.googleapis.com/build-id: '{"worker":"29e8024e-fbd6-4f92-8bb8-d5db790de5a2"}'
    run.googleapis.com/execution-environment: gen1
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: a2893c31-aea2-4d4f-a291-2b287cebcc2c
    autoscaling.knative.dev/maxScale: '5'
  ownerReferences:
  - kind: Configuration
    name: image-search
    uid: 74f3d5c6-cfb5-411a-96ce-4be1a0629ae5
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 1000
  timeoutSeconds: 60
  serviceAccountName: image-search@what-is-pill.iam.gserviceaccount.com
  containers:
  - name: worker
    image: asia-northeast1-docker.pkg.dev/what-is-pill/gcf-artifacts/image--search@sha256:98fd8605ae7ba6fa9b0e46eace5a11e308c9cd8131a606d3de77d34c2059c7c3
    ports:
    - name: http1
      containerPort: 8080
    env:
    - name: LOG_EXECUTION_ID
      value: 'true'
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
    startupProbe:
      timeoutSeconds: 60
      periodSeconds: 240
      failureThreshold: 1
      tcpSocket:
        port: 8080
  runtimeClassName: run.googleapis.com/linux-base-image-update
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-11-21T12:55:08.697306Z'
  - type: Active
    status: 'True'
    lastTransitionTime: '2024-11-21T12:55:08.762767Z'
    severity: Info
  - type: ContainerHealthy
    status: 'True'
    message: Container became healthy in 1.063672s.
    lastTransitionTime: '2024-11-21T12:55:08.637658Z'
  - type: ContainerReady
    status: 'True'
    message: Container image import completed.
    lastTransitionTime: '2024-11-21T12:55:04.419714Z'
  - type: ResourcesAvailable
    status: 'True'
    message: Revision deployment finished in 2.905514s. Checking container health.
    lastTransitionTime: '2024-11-21T12:55:07.322093Z'
  logUrl: https://console.cloud.google.com/logs/viewer?project=what-is-pill&resource=cloud_run_revision/service_name/image-search/revision_name/image-search-00065-zvq&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22image-search%22%0Aresource.labels.revision_name%3D%22image-search-00065-zvq%22
  imageDigest: asia-northeast1-docker.pkg.dev/what-is-pill/gcf-artifacts/image--search@sha256:98fd8605ae7ba6fa9b0e46eace5a11e308c9cd8131a606d3de77d34c2059c7c3
  containerStatuses:
  - name: worker
    imageDigest: asia-northeast1-docker.pkg.dev/what-is-pill/gcf-artifacts/image--search@sha256:98fd8605ae7ba6fa9b0e46eace5a11e308c9cd8131a606d3de77d34c2059c7c3
