apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wip-deep-learning-server-v2
  namespace: '275975834834'
  selfLink: /apis/serving.knative.dev/v1/namespaces/275975834834/services/wip-deep-learning-server-v2
  uid: 980ea830-4c8d-4f0d-8b6c-0546da0a1baf
  resourceVersion: AAYna3ycibk
  generation: 77
  creationTimestamp: '2024-08-19T12:15:37.475189Z'
  labels:
    commit-sha: 6730d56033fbe0352537f1028464a36c03b2cd17
    gcb-build-id: d54c0a50-d582-4a42-8d0d-7a9cb06b3842
    gcb-trigger-id: 2b2bf68b-2179-4aca-a621-4f086cce043e
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    serving.knative.dev/creator: knut043mbm@gmail.com
    serving.knative.dev/lastModifier: knut043mbm@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: 1cca30ff-5749-4cbd-a09c-bbb9b98c834d
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://wip-deep-learning-server-v2-275975834834.asia-northeast1.run.app","https://wip-deep-learning-server-v2-nmlfgqqyva-an.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 39d44b2e-43de-429f-829e-0a8ae79409ae
        commit-sha: 6730d56033fbe0352537f1028464a36c03b2cd17
        gcb-build-id: d54c0a50-d582-4a42-8d0d-7a9cb06b3842
        gcb-trigger-id: 2b2bf68b-2179-4aca-a621-4f086cce043e
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/startup-cpu-boost: 'false'
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 60
      serviceAccountName: image-search@what-is-pill.iam.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: gcr.io/what-is-pill/wip-deep-learning-server-v2
        args:
        - DL_SERVER_PORT=16262
        ports:
        - name: http1
          containerPort: 16262
        env:
        - name: DL_SERVER_PORT
          value: '16262'
        - name: GOOGLE_CLOUD_LOGGING_DISABLE
          value: 'true'
        resources:
          limits:
            cpu: 1000m
            memory: 1280Mi
        startupProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 60
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 16262
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 77
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-11-21T12:34:25.881529Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-11-21T12:34:24.571113Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-11-21T12:34:25.832658Z'
  latestReadyRevisionName: wip-deep-learning-server-v2-00060-f9w
  latestCreatedRevisionName: wip-deep-learning-server-v2-00060-f9w
  traffic:
  - revisionName: wip-deep-learning-server-v2-00060-f9w
    percent: 100
    latestRevision: true
  url: https://wip-deep-learning-server-v2-nmlfgqqyva-an.a.run.app
  address:
    url: https://wip-deep-learning-server-v2-nmlfgqqyva-an.a.run.app
