apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: initial-info
  namespace: '275975834834'
  selfLink: /apis/serving.knative.dev/v1/namespaces/275975834834/services/initial-info
  uid: 2ac954ff-4c0f-4a22-884e-366e3fe7b0b0
  resourceVersion: AAYna7Dz/SY
  generation: 43
  creationTimestamp: '2024-08-17T14:07:24.136488Z'
  labels:
    goog-managed-by: cloudfunctions
    goog-cloudfunctions-runtime: nodejs20
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    serving.knative.dev/creator: service-275975834834@gcf-admin-robot.iam.gserviceaccount.com
    serving.knative.dev/lastModifier: knut043mbm@gmail.com
    run.googleapis.com/custom-audiences: '["https://asia-northeast1-what-is-pill.cloudfunctions.net/initial-info"]'
    run.googleapis.com/client-name: cloud-console
    cloudfunctions.googleapis.com/function-id: initial-info
    run.googleapis.com/build-source-location: gs://run-sources-what-is-pill-asia-northeast1/initial-info/function-source.zip#1732193210811056
    run.googleapis.com/build-function-target: initInfo
    run.googleapis.com/build-service-account: projects/what-is-pill/serviceAccounts/275975834834-compute@developer.gserviceaccount.com
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-base-image: asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20
    run.googleapis.com/build-image-uri: asia-northeast1-docker.pkg.dev/what-is-pill/gcf-artifacts/initial--info:version_1
    run.googleapis.com/build-name: projects/275975834834/locations/asia-northeast1/builds/4dfb7113-d8e8-4d5e-833d-cb10e1446f8e
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: aec656e0-0d63-49ae-a73f-ac7ba4ed37d7
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://initial-info-275975834834.asia-northeast1.run.app","https://asia-northeast1-what-is-pill.cloudfunctions.net/initial-info","https://initial-info-nmlfgqqyva-an.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 276a9fa5-243d-4004-81b5-c5e1cb5e72a1
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/client-name: cloud-console
        cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/startup-cpu-boost: 'false'
        run.googleapis.com/base-images: '{"worker":"asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20"}'
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 10
      serviceAccountName: image-search@what-is-pill.iam.gserviceaccount.com
      containers:
      - name: worker
        image: asia-northeast1-docker.pkg.dev/what-is-pill/gcf-artifacts/initial--info:version_1
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: LOG_EXECUTION_ID
          value: 'true'
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        startupProbe:
          timeoutSeconds: 10
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 43
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-11-21T12:49:04.027942Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-11-21T12:49:03.097764Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-11-21T12:49:03.987110Z'
  latestReadyRevisionName: initial-info-00043-fwk
  latestCreatedRevisionName: initial-info-00043-fwk
  traffic:
  - revisionName: initial-info-00043-fwk
    percent: 100
    latestRevision: true
  url: https://initial-info-nmlfgqqyva-an.a.run.app
  address:
    url: https://initial-info-nmlfgqqyva-an.a.run.app
