apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: drug-detail
  namespace: '275975834834'
  selfLink: /apis/serving.knative.dev/v1/namespaces/275975834834/services/drug-detail
  uid: e92ca255-a471-4c15-a237-f6490851dfe1
  resourceVersion: AAYnlmwDyAc
  generation: 3
  creationTimestamp: '2024-11-23T14:45:41.690965Z'
  labels:
    goog-managed-by: cloudfunctions
    goog-cloudfunctions-runtime: nodejs20
    goog-drz-cloudfunctions-id: drug-detail
    goog-drz-cloudfunctions-location: asia-northeast1
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    serving.knative.dev/creator: service-275975834834@gcf-admin-robot.iam.gserviceaccount.com
    serving.knative.dev/lastModifier: knut043mbm@gmail.com
    run.googleapis.com/custom-audiences: '["https://asia-northeast1-what-is-pill.cloudfunctions.net/drug-detail"]'
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/build-source-location: gs://run-sources-what-is-pill-asia-northeast1/services/drug-detail/1732376064.447000.zip#1732376064709174
    run.googleapis.com/build-function-target: drugDetail
    run.googleapis.com/build-service-account: projects/what-is-pill/serviceAccounts/275975834834-compute@developer.gserviceaccount.com
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-base-image: asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20
    run.googleapis.com/build-image-uri: asia-northeast1-docker.pkg.dev/what-is-pill/gcf-artifacts/what--is--pill__asia--northeast1__drug--detail:version_1
    run.googleapis.com/build-name: projects/275975834834/locations/asia-northeast1/builds/1253aca1-b2d1-40da-a607-3eef5797348f
    cloudfunctions.googleapis.com/function-id: drug-detail
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: 32e31c48-6570-41e2-b08d-d28d1ddf1293
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://drug-detail-275975834834.asia-northeast1.run.app","https://asia-northeast1-what-is-pill.cloudfunctions.net/drug-detail","https://drug-detail-nmlfgqqyva-an.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 75d7bfed-b881-46ec-afa1-5fd60d3b111f
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: cloud-console
        cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/startup-cpu-boost: 'false'
        run.googleapis.com/base-images: '{"worker":"asia-northeast1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20"}'
    spec:
      containerConcurrency: 100
      timeoutSeconds: 60
      serviceAccountName: image-search@what-is-pill.iam.gserviceaccount.com
      containers:
      - name: worker
        image: asia-northeast1-docker.pkg.dev/what-is-pill/cloud-run-source-deploy/drug-detail@sha256:e5ce32a937da66b2bc41b23db64431fa2541ba119c6860745269d819e900445c
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: LOG_EXECUTION_ID
          value: 'true'
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
        startupProbe:
          timeoutSeconds: 60
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 3
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-11-23T15:47:51.028743Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-11-23T15:47:49.780960Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-11-23T15:47:50.993613Z'
  latestReadyRevisionName: drug-detail-00003-tzw
  latestCreatedRevisionName: drug-detail-00003-tzw
  traffic:
  - revisionName: drug-detail-00003-tzw
    percent: 100
    latestRevision: true
  url: https://drug-detail-nmlfgqqyva-an.a.run.app
  address:
    url: https://drug-detail-nmlfgqqyva-an.a.run.app
